### ISSUE TITLE
Loofah::HTML5::WhiteList is deprecated

### ISSUE THREAD

**Issue by vividtone** [rails/rails-html-sanitizer#101]
A warning message "constant Loofah::HTML5::WhiteList is deprecated" is shown if you update Loofah to 2.3.0.

In Loofah 2.3.0, Loofah::HTML5::WhiteList was renamed to Loofah::HTML5::SafeList.
https://github.com/flavorjones/loofah/pull/164

**Comment by bary822** [comment]
I guess this should be fixed in the newest version?
https://github.com/rails/rails-html-sanitizer/pull/100/files

**Comment by vividtone** [comment]
> I guess this should be fixed in the newest version?
> #100

@bary822 Oh, I overlooked the pull request. Thank you for pointing it out.
