### ISSUE TITLE
Please add required_ruby_version to gemspec

### ISSUE THREAD

**Issue by jeremyevans** [rails/rails-html-sanitizer#153]
I would recommend required_ruby_version be set to 2.0.0, since rails-html-sanitizer 1.5.0 uses keyword arguments (at least due to b19975ffcfbda55f4d90fc5f1910770f85bc4de5).  I had CI jobs fail on Ruby 1.9.3 because they tried to load rails-html-sanitizer 1.5.0.  The same CI jobs passed on Ruby 2.0.0.

**Comment by flavorjones** [comment]
@jeremyevans Will do.

**Comment by flavorjones** [comment]
@jeremyevans I forgot I did this a couple of weeks ago already, in https://github.com/rails/rails-html-sanitizer/pull/151
