### ISSUE TITLE
This gem breaks ActionMailer + ActionView + ActiveRecord - Rails projects

### ISSUE THREAD

**Issue by betesh** [rails/rails-html-sanitizer#26]
I have a project that uses ActiveRecord and ActionView (for ActionMailer templates) without Rails.

At https://github.com/rails/rails/blob/v4.2.0/activerecord/lib/active_record/connection_handling.rb#L3, ActiveRecord makes a (reasonable) assumption that if Rails is defined, Rails responds to `env`.  This gem violates that contract in https://github.com/rails/rails-html-sanitizer/blob/v1.0.1/lib/rails/html/sanitizer.rb#L1, which is immediately loaded when you `require "action_view/helpers"`.

Minimal implementation: https://gist.github.com/betesh/f080b8a38ba7f476b2a0

**Comment by rafaelfranca** [comment]
It is also a peperclip bug. Of course a lot of gems will have to adapt their code but I don't see any reason to us avoid to use the Rails namespace as we did at this gem.

**Comment by rafaelfranca** [comment]
Closing since https://github.com/rails/rails/commit/595f7b0f323184b1ac8725c1bb7230a1a9d1800f fixed it.

**Comment by betesh** [comment]
@rafaelfranca As for the README, how do you feel about changing it to "Rails Html Sanitizer is only intended fox use with ActionView, a component of Ruby-on-Rails"?  Is there a more precise word than component?
