### ISSUE TITLE
Custom Scrubber documentation

### ISSUE THREAD

**Issue by burmashave** [rails/rails-html-sanitizer#38]
Not an issue, just a question about the documentation. I know I can whitelist a group of tags like this:
`<%= sanitize comment.content, tags: %w(b i) %>`

Now if want to use a custom scrubber to do the **exact same thing**, it's not clear to me what that would look like. I'd like to use this in the views:
`<%= sanitize comment.content, scrubber: CommentScrubber.new %>`

... but what would CommentScrubber look like? I've tried a few different ways using the example in the 'Custom Scrubber' section of the README but nothing seems to work.

**Comment by kaspth** [comment]
There's an example of `CommentScrubber` just above the line you quote: https://github.com/rails/rails-html-sanitizer#custom-scrubbers

**Comment by burmashave** [comment]
Yes, I saw the example, but it still wasn't clear. What I'm trying to understand is how to make a custom scrubber that does nothing but whitelist a set of tags, such as only "b" and "i". What do I use for this? `allowed_node?` didn't work for me.

**Comment by kaspth** [comment]
Maybe you can make due with the `PermitScrubber`:

```ruby
def comment_scrubber
  @comment_scrubber ||= PermitScrubber.new.tap { |s| s.tags = %w(b i) }
end
```

Read more here: https://github.com/rails/rails-html-sanitizer/blob/master/lib/rails/html/scrubbers.rb

**Comment by burmashave** [comment]
That works. Thanks!
