### ISSUE TITLE
< (less than bracket) is stripped

### ISSUE THREAD

**Issue by smidwap** [rails/rails-html-sanitizer#39]
I'm using the white list sanitizer, and it looks like it strips `<` even if it doesn't form a true html tag.

```
helper.sanitize("the event happened < 2 weeks ago")
=> "the event happened "
```

Is this expected behavior? Doesn't seem quite right.

Thanks in advance!

**Comment by rafaelfranca** [comment]
Yes, it does. It will strip any non closed tag. In your case you have one unclosed tag `< 2 weeks ago`. You must escape the `<`.

**Comment by smidwap** [comment]
Thanks for the rapid response.

Isn't this strange default behavior? Seems like the sanitizer should leave alone `<` if followed by a space.  It's perfectly reasonable user input. Am I missing a security issue?

**Comment by rafaelfranca** [comment]
> Am I missing a security issue?

Yes. given `< script >` as input it will leave it alone and you will get XSS in your page.

**Comment by smidwap** [comment]
Got it. Thanks!

**Comment by rafaelfranca** [comment]
Or even worse. Given you have two `sanitize` calls:

```
user_input_1 = '< script'
user_input_2 = '>'

sanitize(user_input_1)
sanitize(user_input_2)
```

This also lead XSS
