### ISSUE TITLE
What's the plan for JRuby?

### ISSUE THREAD

**Issue by jkraemer** [rails/rails-html-sanitizer#42]
I recently had a look into Loofahs (and by extension this gems) test failures on JRuby. While basic sanitization through Loofah / Nokogiri-J still appears to do what it should, such a massive amount of test failures might turn off potential users of Rails in a Java / JRuby environment and is imho a no-go for anything remotely security relevant.

Are there any plans to support sanitizers not based on Loofah through this gem? I'm asking because I recently came up with a [sanitizer](https://github.com/jkraemer/rails-html-sanitizer-jruby) for JRuby that wraps the [OWASP Java HTML Sanitizer](https://www.owasp.org/index.php/OWASP_Java_HTML_Sanitizer_Project) which I think is at least at the moment a much better solution than relying on Loofah on top of the apparently somewhat flaky Java-Implementation of Nokogiri.

**Comment by rafaelfranca** [comment]
Yes, we have plans to support more than just Loofah as sanitizers although we don't know when this will be implemented

**Comment by kaspth** [comment]
@jkraemer feel free to take a swing at it to speed up the process if you want :smile:
