### ISSUE TITLE
WhiteListSanitizer#sanitize does not work as expected

### ISSUE THREAD

**Issue by chumakoff** [rails/rails-html-sanitizer#46]
Rails::Html::WhiteListSanitizer.new.sanitize("one < two")
=> "one "

Related issues: 
https://github.com/rails/rails/issues/23230
https://github.com/sparklemotion/nokogiri/issues/1419
https://github.com/flavorjones/loofah/issues/99

Rails 4.2.4
rails-html-sanitizer 1.0.2

**Comment by kaspth** [comment]
Can reproduce this with vanilla Nokogiri:

```irb
irb(main):002:0> Nokogiri::HTML::DocumentFragment.parse('one < two')
=> #<Nokogiri::HTML::DocumentFragment:0x3fe1c94a40e4 name="#document-fragment" children=[#<Nokogiri::XML::Text:0x3fe1c9420078 "one ">]>
irb(main):003:0> Nokogiri::HTML::DocumentFragment.parse('one < two').to_s
=> "one "
```

So let's pool resources on sparklemotion/nokogiri#1419 instead of filing 4 issues. Thanks! :heart:

**Comment by flavorjones** [comment]
Nokogiri is operating as expected here. Not sure there's anything anyone can do about invalid HTML being treated as invalid HTML by an HTML parser. Either avoid passing it into the HTML parser or else escape entities first.
