### ISSUE TITLE
Tests failing with libxml2-2.9.3

### ISSUE THREAD

**Issue by pvalena** [rails/rails-html-sanitizer#49]
When i update to libxml2-2.9.3, these tests fail:

SanitizersTest#test_strip_links_with_tags_in_tags
SanitizersTest#test_strip_nested_tags
SanitizersTest#test_should_sanitize_script_tag_with_multiple_open_brackets
SanitizersTest#test_strip_tags_with_many_open_quotes
SanitizersTest#test_strip_invalid_html

http://paste.fedoraproject.org/315402/17785145/

Tests do not fail with libxml2-2.9.2.
Maybe this is related to issue #44, but i cannot reproduce it with neither libxml2 libraries.
I am using rails 4.2.5.

**Comment by flavorjones** [comment]
@pvalena What version of nokogiri did you have installed when these tests failed? Can you provide the output from `nokogiri -v`, please?

Also, the "paste" link above is not valid.

**Comment by pvalena** [comment]
Sorry, the paste must have expired. This one should be 'forever': http://ur1.ca/om1mr

HIH
---
$ nokogiri -v
# Nokogiri (1.6.7.2)
    ---
    warnings: []
    nokogiri: 1.6.7.2
    ruby:
      version: 2.3.0
      platform: x86_64-linux
      description: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
      engine: ruby
    libxml:
      binding: extension
      source: system
      compiled: 2.9.3
      loaded: 2.9.3
