### ISSUE TITLE
Allow "tel:" links

### ISSUE THREAD

**Issue by DannyBen** [rails/rails-html-sanitizer#52]
Hello,

Is it intentional that `tel:` links are not allowed? Seems like a harmless protocol that should be allowed

```
>> sanitize("<a href='http://123'>click</a>")
=> "<a href=\"http://123\">click</a>"
>> sanitize("<a href='tel:123'>click</a>")
=> "<a>click</a>"
```

As a workaround, I am currently using:

```ruby
# config/initializers/sanitize.rb
Loofah::HTML5::WhiteList::ALLOWED_PROTOCOLS.add('tel')
```

As proposed by [this StackOverflow][1] answer

[1]: http://stackoverflow.com/questions/35670896/why-are-tel-links-removed-in-sanitization-and-how-to-allow-them/35671276#35671276

**Comment by kaspth** [comment]
As your workaround shows, this is controlled by Loofah. Try asking there, thanks! 😁
