### ISSUE TITLE
Full sanitizer does not escape quotes

### ISSUE THREAD

**Issue by srecnig** [rails/rails-html-sanitizer#56]
hey,

i've found the following behaviour: `<`, `>` and `&` are escaped when using the sanitizer, while `"` is not.

```
irb -r rails-html-sanitizer.rb
Rails::Html::Sanitizer.full_sanitizer.new.sanitize("lt < and something")
=> "lt &lt; and something"
Rails::Html::Sanitizer.full_sanitizer.new.sanitize("gt > and something")
=> "gt &gt; and something"
Rails::Html::Sanitizer.full_sanitizer.new.sanitize("amp & and something")
=> "amp &amp; and something"
Rails::Html::Sanitizer.full_sanitizer.new.sanitize("quote \" and something")
=> "quote \" and something"

```

Before https://github.com/rails/rails-html-sanitizer/commit/49dfc1584c5b8e35a4ffabf8356ba3df025e8d3f , the full sanitizer was using loofah's `text` method which did escape quotes, but now it's using `to_html`, which does not.

```
Loofah.fragment("quote \" ").to_html
=> "quote \" "
Loofah.fragment("quote \" ").text
=> "quote &quot; "
Loofah.fragment("amp & ").to_html
=> "amp &amp; "
Loofah.fragment("amp & ").text
=> "amp &amp; "
```

Is this a bug or expected behaviour? Should `sanitize` escape quotes or not? Or i am i missing something altogether?

Thanks

**Comment by kaspth** [comment]
The commit you linked to has the reasoning for why we can't escape quotes:

> This introduced a security bug because an attacker can pass escaped HTML
tags that will not be sanitized and will be returned as unescaped HTML
tags.

If you know what you're doing security-wise, you can try using Loofah directly as described here: https://github.com/rails/rails-html-sanitizer/issues/48#issuecomment-175249914

**Comment by rafaelfranca** [comment]
@kaspth That is only about the unescaping behavior but I believe not escaping quotes was not a conscious decision.

**Comment by kaspth** [comment]
Ah, I see 👍

**Comment by srecnig** [comment]
What I (or rather: the [meta-tags gem](https://github.com/kpumuk/meta-tags)) need is a string stripped from html tags that has either both ampersands and quotes escaped or both not escaped. That's currently not possible with rails-html-sanitizer, right?

As of now, i'm stripping tags using the sanitizer, re-encoding all the html special chars using loofah, and then escaping the string again, using the rails html_escape method to make sure quotes and amps are escaped exactly once. 

This feels hacky, but I can't see a better way to make it happen now. Any other ideas?

**Comment by flavorjones** [comment]
It's been quite a few years since this behavior changed and this issue was opened, and I apologize for that.

The current behavior matches the [HTML5 serialization specification](https://www.w3.org/TR/2008/WD-html5-20080610/serializing.html#escapingString) which says:

> Escaping a string (for the purposes of the algorithm above) consists of replacing any occurrences of the "&" character by the string "&amp;", any occurrences of the "<" character by the string "&lt;", any occurrences of the ">" character by the string "&gt;", any occurrences of the U+00A0 NO-BREAK SPACE character by the string "&nbsp;", and, if the algorithm was invoked in the attribute mode, any occurrences of the """ character by the string "&quot;".

Note that "attribute mode" refers to whether the string is an attribute value or not (double-quotes will be escaped if they are part of the attribute value, but not in any other strings).

So, while I get that it was probably inconvenient for your use case, I think that Nokogiri / Loofah / rails-html-sanitizer are doing the right thing in this case.
