### ISSUE TITLE
Sanitize method adds line breaks where they do not exist

### ISSUE THREAD

**Issue by gkaemmer** [rails/rails-html-sanitizer#59]
Running Rails 4.2.0, I get weird behavior when running `sanitize` on the following HTML:
```
<div>
  <div>
    <input>
  </div><div></div>
</div>
```
The method seems to add a line break between the two inner `div`s, resulting in this:
```
<div>
  <div>
    <input>
  </div>
<div></div>
</div>
```
I noticed this because that extra `\n` broke one of my layouts (due to `inline-block` divs with width `50%`. A single piece of whitespace causes wrapping).

The extra line break only happens when there's an input element (AKA an element that doesn't need a closing tag), so I assume it is not expected behavior. Don't know what could be causing this, but thought I'd point it out.

**Comment by kaspth** [comment]
We just use Loofah under the head, ask there for more help ❤️
