### ISSUE TITLE
removing HTML comments

### ISSUE THREAD

**Issue by stefanosc** [rails/rails-html-sanitizer#62]
I am having a hard time removing HTML comments using a custom scrubber. I would appreciate some help.

Following the documentation here is what I tried:
```ruby
scrubber = Rails::Html::TargetScrubber.new
scrubber.tags = ['comment']
white_list_sanitizer = Rails::Html::WhiteListSanitizer.new
white_list_sanitizer.sanitize(@article.body, scrubber: scrubber)
```

However, the HTML comment is not removed in the output string. Am I missing something?
Thank you very much.

**Comment by rafaelfranca** [comment]
comment is not a tag so you can't remove it like this. In this case I believe you would have to write a custom scrubber.

**Comment by stefanosc** [comment]
Hello @rafaelfranca thank you for the message. I find your reply confusing in regards to the readme and the code. 
See [sanitizer.rb#L3](https://github.com/rails/rails-html-sanitizer/blob/master/lib/rails/html/sanitizer.rb#L3)
please also see the following screenshot from the [readme](https://github.com/rails/rails-html-sanitizer#custom-scrubbers):
![screenshot-github com-2017-03-06-19-49-10](https://cloud.githubusercontent.com/assets/4052799/23624505/35505f16-02a6-11e7-955f-9197aa774ba8.jpeg)

What is the "comment" tag if not the HTML comment I am referring to?
Thank you very much.

**Comment by kaspth** [comment]
Been a long time since I've looked at that code. It's entirely possible that the `CommentScrubber` example is wrong when it comes to comments.

The fact that we include `comment()` in `XPATHS_TO_REMOVE` says as much, I think.

Please do investigate! 😊

**Comment by stefanosc** [comment]
Thank you @kaspth yes I am indeed investigating. I believe I found a bug (or at least an unexpected behavior). I will open another issue as soon as I have enough data. Thank you for your work! 🙏

**Comment by kaspth** [comment]
Sweet, sounds good! 😄

**Comment by zavan** [comment]
In my case I wanted to also remove comments and cdata completely. This is what I did:

```ruby
class MyScrubber < Rails::Html::PermitScrubber
  # Override to remove comments and CDATA.
  # SEE: https://github.com/rails/rails-html-sanitizer/issues/62
  def scrub(node)
    if node.cdata? || node.comment?
      scrub_node(node)
    else
      super
    end
  end
end

sanitized = Rails::Html::SafeListSanitizer.new.sanitize(html, scrubber: Scrubber.new)
```
