### ISSUE TITLE
FullSantitizer de-escapes escaped HTML entities besides &, <, >

### ISSUE THREAD

**Issue by miloprice** [rails/rails-html-sanitizer#67]
If you use FullSanitizer on a string containing an escaped &, <, or >, it remains escaped, as discussed [here](https://github.com/rails/rails-html-sanitizer/issues/28) and added [here](https://github.com/rails/rails-html-sanitizer/commit/49dfc1584c5b8e35a4ffabf8356ba3df025e8d3f):

    > Rails::Html::FullSanitizer.new.sanitize("Read more &amp; &lt; &gt;")
    => "Read more &amp; &lt; &gt;"

(using version 1.03 with Ruby 2.3.4)

But if you use it on strings containing other escaped characters, they become de-escaped:

    > Rails::Html::FullSanitizer.new.sanitize("Read more&hellip;")
    => "Read more…"
    > Rails::Html::FullSanitizer.new.sanitize("Save&nbsp;8&euro; &amp; 5&cent;")
    => "Save 8€ &amp; 5¢"

Is this intended behavior? Thanks!

**Comment by kaspth** [comment]
Yes, it is https://github.com/rails/rails/issues/25996#issuecomment-236350744

**Comment by miloprice** [comment]
@kaspth The problem I'm having is that it's **de**-escaping some HTML entities.

`&` gets escaped and becomes `&amp;`, and `&amp;` gets left alone, but `&hellip;` e.g. gets de-escaped and becomes `…`. Why do `&amp;` and `&hellip;` behave differently?

**Comment by kaspth** [comment]
Not sure. I'd check with the Loofah or Nokogiri folks. 😊
