### ISSUE TITLE
test failures with new loofah (2.2.1)

### ISSUE THREAD

**Issue by boutil** [rails/rails-html-sanitizer#70]
Hi,

In newer version, loofah changed from homemade regexps to the crass gem to handle css parsing/scrubbing.
As a  consequence, the output of scrubbing changed a little bit, and additional spaces which were present after the ":" are now removed, causing test failures:

```
SanitizersTest#test_should_sanitize_illegal_style_properties [/home/boutil/debian/ruby-team/ruby-rails-html-sanitizer/test/sanitizer_test.rb:392]:
--- expected
+++ actual
@@ -1 +1 @@
-"display: block; width: 100%; height: 100%; background-color: black; background-x: center; background-y: center;"
+"display:block;width:100%;height:100%;background-color:black;background-x:center;background-y:center;"

SanitizersTest#test_should_sanitize_with_trailing_space [/home/boutil/debian/ruby-team/ruby-rails-html-sanitizer/test/sanitizer_test.rb:398]:
Expected: "display: block;"
  Actual: "display:block;"
```

Of course, it is just cosmetic and doesn't really break any functionality. Could you adapt the tests to the new output? Maybe these tests could be made more robust to such minor changes of output?

**Comment by rafaelfranca** [comment]
Thanks! Fixed.
